# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170119_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
