# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:14
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('news', '0003_subpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpost',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
