# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170219_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpost',
            name='hiden',
        ),
    ]
