# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_subpost_hiden'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpost',
            name='hiden',
            field=models.BooleanField(default=False),
        ),
    ]
